all:
  vars:
    ansible_connection: docker
    ansible_user: root
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3
    required_total_memory_mb_zookeeper: 100
    required_total_memory_mb_kafka_broker: 100
    required_total_memory_mb_kafka_connect: 100
    required_total_memory_mb_schema_registry: 100
    required_total_memory_mb_ksql: 100 
    required_total_memory_mb_kafka_rest: 100
    required_total_memory_mb_control_center: 100
    create_mds_certs: false
zookeeper:
  hosts:
    zookeeper1:
      zookeeper_id: 1
kafka_broker:
  hosts:
    broker1:
      broker_id: 1
    broker2:
      broker_id: 2
    broker3:
      broker_id: 3
schema_registry:
  hosts:
    schema-registry:
kafka_connect:
  hosts:
    connect:
kafka_rest:
  hosts:
    rest-proxy:
ksql:
  hosts:
    ksql-server:
control_center:
  hosts:
    control-center: