name: CI

on:
  push:
    branches:
      - master

  schedule:
     - cron: '0 3 * * *' # every day at 3 am

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    name: ${{ matrix.tag }}
    strategy:
      fail-fast: false
      matrix:
        tag: ["5.5.10","6.0.8","6.1.6","6.2.5","7.0.4","7.1.2","7.2.0"]
    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u vdesabou --password-stdin
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Free up disk space"
        run: |
          df -h
          sudo apt-get -qq purge build-essential ghc*
          sudo apt-get clean
          docker system prune -af
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h

      - name: Create images
        run: bash scripts/create-image.sh "${{ matrix.tag }}"
